openapi: 3.0.3
info:
  title: Person Service
  description: The Person Service an endpoint to manage Person related tasks
  version: 1.0.0
servers:
  - url: 'https'
paths:
components:
  schemas:
    Person:
      type: object
      description: A Person object describes people
      required:
        - id
        - firstName
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier of the person
        firstName:
          type: string
          description: First name of the person
        lastName:
          type: string
          description: Last name of the person
    Address:
      type: object
      description: The address locates a place on Earth
      properties:
        id:
          type: integer
          format: int64
        street:
          type: string
        poBox:
          type: integer
          format: int64
        
  
