@startuml

entity Document {
    Id
    Name
    Description
    StructureNodeId
    StructureNode tree
    AuthorId
    Author author
    SourceId
    Source source
    User createdBy
    User lastModifiedBy
    Date lastModified
    Date created
}

entity Author {
    id
    PersonId
    Person
}

entity Person {
    id
    Name name
    BirthDate birthDate
    CeaseDate ceaseDate
    BirthPlace birthPlace
    CeasePlace ceasePlace
}

entity Source {
    id
    name
    Url
}

entity StructureNode {
    id
    name
    StructureNode[] nodes
    UIElementInfo uiElementInfo
    StructureInfo structureInfo
}

entity UIElementInfo {}
entity StructureInfo {}

Document::StructureNodeId <-- StructureNode::id
Document::AuthorId <-- Author::Id
Document::SourceId <-- Source::Id
Author::PersonId <-- Person::Id
StructureNode .. StructureNodeType
StructureNode .. UIElementInfo
StructureNode .. StructureInfo

@enduml