title = "Modeling with equations"
reference = "modeling_with_equations"
section_number = 1.7
chapter_reference = "fundamentals"
book_reference = "james_stewart_precalculus"
page_start = 65
page_exercises_start = 75
concepts_questions_interval_start = "1"
concepts_questions_interval_end = "6"
skills_questions_interval_start = "7"
skills_questions_interval_end = "20"
applications_questions_interval_start = "21"
applications_questions_interval_end = "91"
discussion_questions_interval_start = "92"
discussion_questions_interval_end = "93"
page_end = 81
