openapi: 3.0.3
info:
  title: Encyclopedia Galactica Document Api
  description: Encyclopedia Galactica Document Api
  version: 1.0.0
servers:
  - url: 'https://localhost:8080/api/document'
paths:
  '/sourceformatnode/add':
    post:
      description: 'Creates SourceFormatNode entity'
      responses: 
        201:
          description: 'Entity has been created'
          content: 
            'application/json':
              schema: 
                type: object
                items: 
                  $ref: '#/components/schemas/SourceFormatNodeAddModel'
        400:
          description: 'Entity cannot be created due to error in the posted data'
          content: 
            'application/json':
              schema: 
                type: object
                items: 
                  $ref: '#/components/schemas/ErrorModel'
    
  '/sourceformatnode/getall':
    get:
      description: 'Retrieves the list of entities in the system'
      responses: 
        200:
          description: 'Returns the list of entities in the system'
          content: 
            'application/json':
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/SourceFormatNodeModel'
                  
  '/sourceformatnode/update':
    put:
      description: 'Updates the designated entity with the data stored in the provided object'
      responses: 
        200:
          description: 'The designated entity is successfully updated with the provided data'
          content: 
            'application/json':
              schema: 
                type: object
                items: 
                  $ref: 
  '/sourceformatnode/delete':
  '/sourceformatnode/getbyid':
  'sourceformatnode/addchildtoparent':
components: 
  schemas:
    
    ErrorModel:
      description: 'The model contains the error message and details happened in the system'
      type: object
      properties: 
        message:
          type: string
          description: 'Error message'

    SourceFormatNodeAddModel:
      description: 'Describes the expected format for entity creation'
      allOf:
        - $ref: '#/components/schemas/SourceFormatNodeModel'
        - type: object
          properties: 
            id:
              type: number
              maximum: 0
              minimum: 0

    SourceFormatNodeUpdateModel:
      description: 'Describes the expected format for updating the designated entity'
      allOf:
        - $ref: '#/components/schemas/SourceFormatNodeModel'
        - type: object
          properties: 
            id:
              type: number
              minimum: 1
    
    SourceFormatNodeModel:
      type: object
      description: 'Describes the inner structure of a document'
      properties: 
        id:
          type: number
          description: 'Unique identifier'
        name:
          type: string
          description: 'Name of the entity'
          minLength: 3
        is_root_node:
          type: integer
          description: 'Defines if the SourceFormatNode is a root node'
          minimum: 0
          maximum: 1
