@startuml

class Document {
    Long Id
    String Name
    String Description
    Source Source
    Author Author
    Structure Structure
    DocumentType DocumentType
    Format Format
    Form Form
}
note top of Document 
    The Document describes a document in the system
    it pulls together all the information we know about it which
    includes its data and all the information needed for
    its representation
    
    It does not describe the form needed to put data into this
    document format. This one is described by the Form object.
end note

class Form {
    Long Id
    String Name
    String Description
    String FormUiName
    Uri PostUri
    String FormType
    FormStructure[] FormStructures
    Document Document
}

note top of Form
    The Form object describes a form which is, in general, complementary
    of a Document object in the system. Form makes possible to
    feed the Document by data using forms of Encyclopedia Galactica system
end note

class FormStructure {
    Long Id
    String Name
    UIElement[] UIElement
}

note top of FormStructure
    FormStructure describes basically a UI element building up the form
    A good example for this is HTML elements
end note

class UIElement {
    Long Id
    String Name
    String ElementTypeName
    String ElementTypeContent
    Validation[] Validations
}

note top of UIElement
    The UIElement describes the concrete implementation
    For example HTML Input field
end note

class Validation {
    Long Id
    String Name
    String InputType
    String ValidationRule
}

note top of Validation
    Describes how the input data will be validated
end note

class Format {
    Long Id
    String Name
    String Description
}

note top of Format
    Describes the original format of a Document
    It can be for example book, RSS feed, Word document
end note

class Source {
    Long Id
    Uri Uri
}

class Author {
    Long Id
    AuthorType AuthorType
}

class AuthorType {
    Long Id
    String Name
}

class Structure {
    Long Id
    String Name
    String SeparatorBefore
    String SeparatorAfter
    String RawContent
    Structure[] Structure
}

class Sentence {
    Long Id;
    String RawContent
    Word[] Words
}

note top of Sentence
    Describes a text sentence in the Document
end note

class Word{
    Long Id
    String Word
    Character[] Characters
}

note top of Word
    It describes a word
end note

class Character{
    Long Id
    String Name
    Char Character
}

class DocumentType {
    Long Id
    String Name
    String Description
    String FileExtension
}

Document -- Source
Document -- Author
Document -- DocumentType
Author -- AuthorType
Document -- Structure
Structure -- Sentence
Sentence -- Word
Word -- Character
Document -- Format
Document -- Form
Form -- FormStructure
FormStructure -- UIElement
UIElement - Validation
@enduml