title = "Functions"
reference = "functions"
section_number = 2.1
chapter_reference = "functions"
book_reference = "james_stewart_precalculus"
page_start = 148
page_exercises_start = 155
concepts_questions_interval_start = "1"
concepts_questions_interval_end = "8"
skills_questions_interval_start = "9"
skills_questions_interval_end = "82"
applications_questions_interval_start = "83"
applications_questions_interval_end = "98"
discussion_questions_interval_start = "99"
discussion_questions_interval_end = "101"
page_end = 159
