title = "Chapter Review"
section_number = 4.8
chapter_reference = "4_exponential_and_logarithmic_functions"
book_reference = "james_stewart_precalculus"
page_start = 396
page_exercises_start = 396
concepts_questions_interval_start = "1"
concepts_questions_interval_end = "19"
skills_questions_interval_start = "1"
skills_questions_interval_end = "111"
applications_questions_interval_start = "NA"
applications_questions_interval_end = "NA"
discussion_questions_interval_start = "NA"
discussion_questions_interval_end = "NA"
page_end = 401
