title = "Complex numbers"
reference = "complex_numbers"
section_number = 1.6
chapter_reference = "fundamentals"
book_reference = "james_stewart_precalculus"
page_start = 59
page_exercises_start = 63
concepts_questions_interval_start = "1"
concepts_questions_interval_end = "6"
skills_questions_interval_start = "7"
skills_questions_interval_end = "84"
applications_questions_interval_start = "0"
applications_questions_interval_end = "0"
discussion_questions_interval_start = "85"
discussion_questions_interval_end = "86"
page_end = 64
