@startuml
entity Document{
    Long id
    String name
    String desc
    DocumentNode documentNode
    Person author
    Source source
}

entity Person{
    Long id
}

entity Source {
    Long id
    String name
}

entity UIElement {
    Long id
    String name
    String desc
}

entity DocumentNode {
    Long id
    String name
    DocumentNode[] documentNodes
    UIElement[] uiElement
}


Document <|-- Person
Document <|-- DocumentNode
Document <|-- Source

DocumentNode <|-- UIElement
@enduml