title = "Exponential Functions"
section_number = 4.1
chapter_reference = "4_exponential_and_logarithmic_functions"
book_reference = "james_stewart_precalculus"
page_start = 338
page_exercises_start = 344
concepts_questions_interval_start = "1"
concepts_questions_interval_end = "6"
skills_questions_interval_start = "7"
skills_questions_interval_end = "52"
applications_questions_interval_start = "53"
applications_questions_interval_end = "64"
discussion_questions_interval_start = "65"
discussion_questions_interval_end = "66"
page_end = 346
