title = "Real Zeros of Polynomials"
section_number = 3.4
chapter_reference = "3_polynomial_and_rational_functions"
page_start = 281
page_exercises_start = 289
concepts_questions_interval_start = 1
concepts_questions_interval_end = 4
skills_questions_interval_start = 5
skills_questions_interval_end = 98
applications_questions_interval_start = 99
applications_questions_interval_end = 104
discussion_questions_interval_start = 105
discussion_questions_interval_end = 109
page_end = 292
