trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - Doc/**

pool: 'contabo'

variables:
  print_pattern: ' === '
  solution_name: 'EncyclopediaGalactica.sln'
  # Document Service
  document_cacheservice_tests_unit: 'Services/Document/Document.CacheService.Tests.Unit/Document.CacheService.Tests.Unit.csproj'
  document_cacheservice_tests_int: 'Services/Document/Document.CacheService.Tests.Int/Document.CacheService.Tests.Int.csproj'
  document_client_models_tests_unit: 'Services/Document/Document.Client.Models.Tests.Unit/Document.Client.Models.Tests.Unit.csproj'
  document_client_tests_unit: 'Services/Document/Document.Client.Tests.Unit/Document.Client.Tests.Unit.csproj'
  document_client_tests_int: 'Services/Document/Document.Client.Tests.Int/Document.Client.Tests.Int.csproj'
  document_controllers_viewmodels_tests_int: 'Services/Document/Document.Controllers.ViewModels.Tests.Unit/Document.Controllers.ViewModels.Tests.Unit.csproj'
  document_dtos_tests_unit: 'Services/Document/Document.Dtos.Tests.Unit/Document.Dtos.Tests.Unit.csproj'
  document_entities_tests_unit: 'Services/Document/Document.Entities.Tests.Unit/Document.Entities.Tests.Unit.csproj'
  document_mappers_tests_unit: 'Services/Document/Document.Mappers.Tests.Unit/Document.Mappers.Tests.Unit.csproj'
  document_repository_tests_unit: 'Services/Document/Document.Repository.Tests.Unit/Document.Repository.Tests.Unit.csproj'
  document_repository_tests_int: 'Services/Document/Document.Repository.Tests.Int/Document.Repository.Tests.Int.csproj'
  document_service_tests_unit: 'Services/Document/Document.Service.Tests.Unit/Document.Service.Tests.Unit.csproj'
  document_service_tests_int: 'Services/Document/Document.Service.Tests.Int/Document.Service.Tests.Int.csproj'
  document_tests_e2e: 'Services/Document/Document.Tests.E2E/Document.Tests.E2E.csproj'
  
  # Tools
  restapigenerator_tests_unit: 'Tools/Generator/Generator.Tests.Unit/Generator.Tests.Unit.csproj'

stages:
  - stage: Variables
    jobs:
      - job:
        steps:
          - script: |
              echo $PATH
              env | sort

  - stage: Feature_branch
    condition: ne(variables['System.PullRequest.SourceBranch'], '')
    jobs:
      - job: restore_solution
        displayName: Restore Solution
        steps:
          - script: dotnet restore ${{ variables.solution_name }}

      - job: build_solution
        displayName: Build Solution
        dependsOn: restore_solution
        steps:
          - script: dotnet build ${{ variables.solution_name }}

      - job: test_solution
        displayName: Test Solution
        dependsOn: build_solution
        steps:
          - script: |
              echo ${{ variables.print_pattern }} ${{ variables.document_cacheservice_tests_unit }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_cacheservice_tests_unit }}
              
              echo ${{ variables.print_pattern }} ${{ variables.document_cacheservice_tests_int }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_cacheservice_tests_int }}
              
              echo ${{ variables.print_pattern }} ${{ variables.document_client_models_tests_unit }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_client_models_tests_unit }}
              
              echo ${{ variables.print_pattern }} ${{ variables.document_client_tests_unit }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_client_tests_unit }}
              
              echo ${{ variables.print_pattern }} ${{ variables.document_client_tests_int }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_client_tests_int }}
              
              echo ${{ variables.print_pattern }} ${{ variables.document_controllers_viewmodels_tests_int }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_controllers_viewmodels_tests_int }}
              
              echo ${{ variables.print_pattern }} ${{ variables.document_dtos_tests_unit }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_dtos_tests_unit }}
              
              echo ${{ variables.print_pattern }} ${{ variables.document_entities_tests_unit }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_entities_tests_unit }}
              
              echo ${{ variables.print_pattern }} ${{ variables.document_mappers_tests_unit }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_mappers_tests_unit }}
              
              echo ${{ variables.print_pattern }} ${{ variables.document_repository_tests_unit }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_repository_tests_unit }}
              
              echo ${{ variables.print_pattern }} ${{ variables.document_repository_tests_int }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_repository_tests_int }}
              
              echo ${{ variables.print_pattern }} ${{ variables.document_service_tests_unit }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_service_tests_unit }}
              
              echo ${{ variables.print_pattern }} ${{ variables.document_service_tests_int }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_service_tests_int }}
              
              echo ${{ variables.print_pattern }} ${{ variables.document_tests_e2e }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_tests_e2e }}
              
              echo ${{ variables.print_pattern }} ${{ variables.restapigenerator_tests_unit }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.restapigenerator_tests_unit }}

  - stage: Main_branch
    condition: and(eq(variables['System.PullRequest.SourceBranch'], ''), eq(variables['Build.SourceBranch'],'refs/heads/main'))
    jobs:
      - job: restore_solution
        displayName: Restore Solution
        steps:
          - script: dotnet restore ${{ variables.solution_name }}

      - job: build_solution
        displayName: Build Solution
        dependsOn: restore_solution
        steps:
          - script: dotnet build ${{ variables.solution_name }}

      - job: test_solution
        displayName: Test Solution
        dependsOn: build_solution
        steps:
          - script: |
              echo ${{ variables.print_pattern }} ${{ variables.document_cacheservice_tests_unit }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_cacheservice_tests_unit }}
              
              echo ${{ variables.print_pattern }} ${{ variables.document_cacheservice_tests_int }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_cacheservice_tests_int }}
              
              echo ${{ variables.print_pattern }} ${{ variables.document_client_models_tests_unit }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_client_models_tests_unit }}
              
              echo ${{ variables.print_pattern }} ${{ variables.document_client_tests_unit }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_client_tests_unit }}
              
              echo ${{ variables.print_pattern }} ${{ variables.document_client_tests_int }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_client_tests_int }}
              
              echo ${{ variables.print_pattern }} ${{ variables.document_controllers_viewmodels_tests_int }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_controllers_viewmodels_tests_int }}
              
              echo ${{ variables.print_pattern }} ${{ variables.document_dtos_tests_unit }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_dtos_tests_unit }}
              
              echo ${{ variables.print_pattern }} ${{ variables.document_entities_tests_unit }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_entities_tests_unit }}
              
              echo ${{ variables.print_pattern }} ${{ variables.document_mappers_tests_unit }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_mappers_tests_unit }}
              
              echo ${{ variables.print_pattern }} ${{ variables.document_repository_tests_unit }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_repository_tests_unit }}
              
              echo ${{ variables.print_pattern }} ${{ variables.document_repository_tests_int }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_repository_tests_int }}
              
              echo ${{ variables.print_pattern }} ${{ variables.document_service_tests_unit }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_service_tests_unit }}
              
              echo ${{ variables.print_pattern }} ${{ variables.document_service_tests_int }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_service_tests_int }}
              
              echo ${{ variables.print_pattern }} ${{ variables.document_tests_e2e }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.document_tests_e2e }}
              
              echo ${{ variables.print_pattern }} ${{ variables.restapigenerator_tests_unit }} ${{ variables.print_pattern }}
              dotnet test ${{ variables.restapigenerator_tests_unit }}

      - job: install_semantic
        dependsOn: test_solution
        displayName: Install Semantic
        steps:
          - script: |
              echo '##vso[task.prependpath]$(HOME)/.local/bin'
            displayName: PATH
          - script: |
              npm install npm
            displayName: npm
          - script: |
              npm install semantic-release
            displayName: semantic-release
          - script: |
              npm install @semantic-release/changelog
            displayName: semantic-release/changelog
          - script: |
              npm install @semantic-release/exec
            displayName: semantic-release/exec
          - script: |
              npm install @semantic-release/git
            displayName: semantic-release/git
          - script: |
              npm install @semantic-release/github
            displayName: semantic-release/github
          - script: |
              pip3 install --user bump2version
            displayName: bump2version

      - job: semantic_release
        dependsOn: install_semantic
        displayName: Semantic Release
        steps:
          - script: |
              echo '##vso[task.prependpath]$(HOME)/.local/bin'
            displayName: PATH
          - script: |
              npx semantic-release
            displayName: semantic-release
            env:
              GH_TOKEN: $(githubToken)

      - job: antora
        dependsOn: semantic_release
        displayName: Antora doc
        steps:
          - script: |
              npx antora -v
              npx antora Doc/antora/antora-playbook.yml --to-dir docs --clean
              git config --global user.email "$(emailAddress)"
              git config --global user.name "$(userName)"
              git add .
              git commit -m "generate doc for publish"
              git push origin gh_pages
            displayName: antora build
            env:
              GITHUB_TOKEN: $(githubToken)
    
