trigger:
  branches:
    include:
      - main
        
pool: 'contabo'

variables:
  solutionName: 'EncyclopediaGalactica.sln'

stages:
  - stage: Main_branch
    jobs:
      - job: restore_solution
        displayName: Restore Solution
        steps:
          - script: dotnet build $solutionName
            
      - job: build_solution
        displayName: Build Solution
        steps:
          - script: dotnet build $solutionName
            
      - job: test_solution
        displayName: Test Solution
        steps:
          - script: dotnet test $solutionName
    