trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - Doc/**

pool: 'contabo'

variables:
  solutionName: 'EncyclopediaGalactica.sln'
  document_cacheservice_tests_unit: 'Services/Document/Document.CacheService.Tests.Unit/Document.CacheService.Tests.Unit.csproj'
  document_cacheservice_tests_int: 'Services/Document/Document.CacheService.Tests.Int/Document.CacheService.Tests.Int.csproj'
  document_client_models_tests_unit: 'Services/Document/Document.Client.Models.Tests.Unit/Document.Client.Models.Tests.Unit.csproj'
  document_client_tests_unit: 'Services/Document/Document.Client.Tests.Unit/Document.Client.Tests.Unit.csproj'
  document_client_tests_int: 'Services/Document/Document.Client.Tests.Int/Document.Client.Tests.Int.csproj'
  document_controllers_viewmodels_tests_int: 'Services/Document/Document.Controllers.ViewModels.Tests.Unit/Document.Controllers.ViewModels.Tests.Unit.csproj'
  document_dtos_tests_unit: 'Services/Document/Document.Dtos.Tests.Unit/Document.Dtos.Tests.Unit.csproj'
  document_entities_tests_unit: 'Services/Document/Document.Entities.Tests.Unit/Document.Entities.Tests.Unit.csproj'
  document_mappers_tests_unit: 'Services/Document/Document.Mappers.Tests.Unit/Document.Mappers.Tests.Unit.csproj'
  document_repository_tests_unit: 'Services/Document/Document.Repository.Tests.Unit/Document.Repository.Tests.Unit.csproj'
  document_repository_tests_int: 'Services/Document/Document.Repository.Tests.Int/Document.Repository.Tests.Int.csproj'
  document_service_tests_unit: 'Services/Document/Document.Service.Tests.Unit/Document.Service.Tests.Unit.csproj'
  document_service_tests_int: 'Services/Document/Document.Service.Tests.Int/Document.Service.Tests.Int.csproj'

stages:
  - stage: Variables
    jobs:
      - job:
        steps:
          - script: |
              echo $PATH
              env | sort

  - stage: Feature_branch
    condition: ne(variables['System.PullRequest.SourceBranch'], '')
    jobs:
      - job: restore_solution
        displayName: Restore Solution
        steps:
          - script: dotnet restore $solutionName

      - job: build_solution
        displayName: Build Solution
        dependsOn: restore_solution
        steps:
          - script: dotnet build $solutionName

      - job: test_solution
        displayName: Test Solution
        dependsOn: build_solution
        steps:
          - script: |
              echo "=== " ${{ variables.document_cacheservice_tests_unit }}
              dotnet test ${{ variables.document_cacheservice_tests_unit }}
              dotnet test ${{ variables.document_cacheservice_tests_int }}
              dotnet test ${{ variables.document_client_models_tests_unit }}
              dotnet test ${{ variables.document_client_tests_unit }}
              dotnet test ${{ variables.document_client_tests_int }}
              dotnet test ${{ variables.document_controllers_viewmodels_tests_int }}
              dotnet test ${{ variables.document_dtos_tests_unit }}
              dotnet test ${{ variables.document_entities_tests_unit }}
              dotnet test ${{ variables.document_mappers_tests_unit }}
              dotnet test ${{ variables.document_repository_tests_unit }}
              dotnet test ${{ variables.document_repository_tests_int }}
              dotnet test ${{ variables.document_service_tests_unit }}
              dotnet test ${{ variables.document_service_tests_int }}

  - stage: Main_branch
    condition: and(eq(variables['System.PullRequest.SourceBranch'], ''), eq(variables['Build.SourceBranch'],'refs/heads/main'))
    jobs:
      - job: restore_solution
        displayName: Restore Solution
        steps:
          - script: dotnet restore $solutionName

      - job: build_solution
        displayName: Build Solution
        dependsOn: restore_solution
        steps:
          - script: dotnet build $solutionName

      - job: test_solution
        displayName: Test Solution
        dependsOn: build_solution
        steps:
          - script: |
              dotnet test ${{ variables.document_cacheservice_tests_unit }}
              dotnet test ${{ variables.document_cacheservice_tests_int }}
              dotnet test ${{ variables.document_client_models_tests_unit }}
    
