use clap::Command;

pub fn list_subcommand(commands: Command) -> Command {
    commands.subcommand(
        Command::new("list")
            .about("Listing the available books and topics.")
            .long_about(
                "
Listing the available books and topics.
It is important to note that TOPICS is a bigger set than BOOKS.
When questions generated by TOPICS the result may have questions across multiple books.
",
            )
            .propagate_version(true)
            .arg_required_else_help(true)
            .subcommands([
                Command::new("books")
                    .about("Listing the available books to generate testing questions."),
                Command::new("topics")
                    .about("Listing the available topics to generate testing questions."),
            ]),
    )
}
