title = "Inequalities"
section_number = 1.8
chapter_reference = "fundamentals"
page_start = 81
page_exercises_start = 89
concepts_questions_interval_start = 1
concepts_questions_interval_end = 6
skills_questions_interval_start = 7
skills_questions_interval_end = 116
applications_questions_interval_start = 117
applications_questions_interval_end = 133
discussion_questions_interval_start = 134
discussion_questions_interval_end = 139
page_end = 91
