@startuml

entity Document {
    Id
    Name
    Description
    StructureId
    Structure tree
    AuthorId
    Author author
    SourceId
    Source source
    User createdBy
    User lastModifiedBy
    Date lastModified
    Date created
}

entity Author {
    id
    PersonId
    Person
}

entity Person {
    id
    Name name
    BirthDate birthDate
    CeaseDate ceaseDate
    BirthPlace birthPlace
    CeasePlace ceasePlace
}

entity Source {
    id
    name
    Url
}

entity Structure {
    id
    name
    Structure[] nodes
    UIElementInfo uiElementInfo
    StructureInfo structureInfo
}

entity UIElementInfo {}
entity StructureInfo {}

Document::StructureId <-- Structure::id
Document::AuthorId <-- Author::Id
Document::SourceId <-- Source::Id
Author::PersonId <-- Person::Id
Structure .. StructureNodeType
Structure .. UIElementInfo
Structure .. StructureInfo

@enduml