title = "Logarithmic Scales"
section_number = 4.7
chapter_reference = "4_exponential_and_logarithmic_functions"
book_reference = "james_stewart_precalculus"
page_start = 391
page_exercises_start = 395
concepts_questions_interval_start = "NA"
concepts_questions_interval_end = "NA"
skills_questions_interval_start = "NA"
skills_questions_interval_end = "NA"
applications_questions_interval_start = "1"
applications_questions_interval_end = "35"
discussion_questions_interval_start = "21"
discussion_questions_interval_end = "21"
page_end = 396
