title = "Transformation of Functions"
section_number = 2.6
chapter_reference = "functions"
book_reference = "james_stewart_precalculus"
page_start = 201
page_exercises_start = 209
concepts_questions_interval_start = "1"
concepts_questions_interval_end = "6"
skills_questions_interval_start = "7"
skills_questions_interval_end = "92"
applications_questions_interval_start = "93"
applications_questions_interval_end = "96"
discussion_questions_interval_start = "97"
discussion_questions_interval_end = "103"
page_end = 214
