title = "Physics Examination - 2015 - Oct - Advanced level - Hungarian"
reference = "physics_examination_2015_oct_advanced_hungarian"
section_number = 2005.1
chapter_reference = "physics_examination_advanced"
book_reference = "high_school_graduation_physics"
page_start = 1
page_exercises_start = 10
concepts_questions_interval_start = "NA"
concepts_questions_interval_end = "NA"
skills_questions_interval_start = "1"
skills_questions_interval_end = "4"
applications_questions_interval_start = "NA"
applications_questions_interval_end = "NA"
discussion_questions_interval_start = "NA"
discussion_questions_interval_end = "NA"
page_end = 10
