name: Feature
run-name: Feature

on:
  pull_request:
    branches:
      - main

jobs:
  
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "============="
          echo "=== Debug ==="
          echo "============="
          echo "github ref: " ${{ vars.GITHUB_REF }}
          echo "dotnet version: " ${{ vars.DOTNET_VERSION }}
          echo "event name: " ${{ github.event_name }}
          
  commons:
    name: EG.Commons
    runs-on: ubuntu-latest
    needs: debug
    
    steps:
      - uses: actions/checkout@v3
        
      - name: Setting up Dotnet with ${{ vars.DOTNET_VERSION }} version
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}
          
      - name: Restore
        run: |
          dotnet restore Common.sln
          
      - name: Build
        run: |
          dotnet build --configuration Debug Common.sln
          
      - name: Test
        run: |
          dotnet test --no-restore --verbosity normal Common.sln
