title = "Getting Information from the Graph of a Function"
reference = "getting_information_from_the_graph_of_a_function"
section_number = 2.3
chapter_reference = "functions"
book_reference = "james_stewart_precalculus"
page_start = 172
page_exercises_start = 180
concepts_questions_interval_start = "1"
concepts_questions_interval_end = "6"
skills_questions_interval_start = "7"
skills_questions_interval_end = "62"
applications_questions_interval_start = "63"
applications_questions_interval_end = "74"
discussion_questions_interval_start = "75"
discussion_questions_interval_end = "76"
page_end = 185
