title = "Chapter Test"
reference = "chapter_test"
section_number = 4.9
chapter_reference = "4_exponential_and_logarithmic_functions"
book_reference = "james_stewart_precalculus"
page_start = 402
page_exercises_start = 402
concepts_questions_interval_start = "1"
concepts_questions_interval_end = "13"
skills_questions_interval_start = "NA"
skills_questions_interval_end = "NA"
applications_questions_interval_start = "NA"
applications_questions_interval_end = "NA"
discussion_questions_interval_start = "NA"
discussion_questions_interval_end = "NA"
page_end = 402
