title = "The Natural Exponential Function"
reference = "the_natural_exponential_function"
section_number = 4.2
chapter_reference = "4_exponential_and_logarithmic_functions"
book_reference = "james_stewart_precalculus"
page_start = 346
page_exercises_start = 349
concepts_questions_interval_start = "1"
concepts_questions_interval_end = "2"
skills_questions_interval_start = "3"
skills_questions_interval_end = "34"
applications_questions_interval_start = "35"
applications_questions_interval_end = "51"
discussion_questions_interval_start = "52"
discussion_questions_interval_end = "52"
page_end = 351
