title = "Rational Functions"
reference = "rational_functions"
section_number = 3.6
chapter_reference = "3_polynomial_and_rational_functions"
book_reference = "james_stewart_precalculus"
page_start = 306
page_exercises_start = 314
concepts_questions_interval_start = "1"
concepts_questions_interval_end = "10"
skills_questions_interval_start = "11"
skills_questions_interval_end = "92"
applications_questions_interval_start = "93"
applications_questions_interval_end = "99"
discussion_questions_interval_start = "100"
discussion_questions_interval_end = "102"
page_end = 318
