title = "Complex Zeros and the Fundamental Theorem of Algebra"
reference = "complex_zeros_and_the_fundamental_theorem_of_algebra"
section_number = 3.5
chapter_reference = "3_polynomial_and_rational_functions"
book_reference = "james_stewart_precalculus"
page_start = 293
page_exercises_start = 299
concepts_questions_interval_start = "1"
concepts_questions_interval_end = "6"
skills_questions_interval_start = "7"
skills_questions_interval_end = "74"
applications_questions_interval_start = "NA"
applications_questions_interval_end = "NA"
discussion_questions_interval_start = "75"
discussion_questions_interval_end = "76"
page_end = 300
