title = "Graphs of Functions"
section_number = 2.2
chapter_reference = "functions"
book_reference = "james_stewart_precalculus"
page_start = 159
page_exercises_start = 168
concepts_questions_interval_start = "1"
concepts_questions_interval_end = "8"
skills_questions_interval_start = "9"
skills_questions_interval_end = "78"
applications_questions_interval_start = "79"
applications_questions_interval_end = "86"
discussion_questions_interval_start = "87"
discussion_questions_interval_end = "90"
page_end = 172
