= Main page

In the Encyclopedia Galactica system everything revolves around the Document.
The Document is the medium which contains information, knowledge, about anything.
The Document is the place where information from different Documents and/or DataSources come together and create information.
Documents are place for collaborative work between Users.

In an ideal case a Document contains a small or logical piece of information and has connection to other Documents.
The system provides functionality to create connection between Documents, or portion of a Documents.
When there is a connection between two Documents or Document parts (a sentence or paragraph for example) the meaning of this relation is not only in that the two Documents are linked together, but also the quality of the relation.
For example, in one Document the word "SOLID" mentioned.
It is possible to link other Documents to this word which:

- definition of SOLID
- to where it belongs to within the software world (Clean Code, Software Delivery, Refactoring, etc)
- what is its history
- its critique
- and so on.

For the reader it is a great help to see the qualifier of a relation between two Documents.

As these connection between Documents with qualifier are collected will be possible to see the map of a field.
At this point we arrived to the world of Thesaurus.

What is the importance of knowing the map of a field and creating a Thesaurus covering it?
This map can help a better understanding of the field.
It highly probably can contribute to better models for AI tools.
Organized and usable knowledge is the most powerful weapon.

The goal of the Encyclopedia Galactica project is to provide a system where:

- documents can be uploaded
- document content can be managed in a versioned way
- connections between documents (a piece of document) and document content (e.g. a paragraph or sentence in the document) can be defined with a qualifier (extends, related, parent, child, etc)
- the relation qualifiers can be used to provide better (more relevant) search and suggestions
- a rich user interface for editing and reading
- documents can be published

There are two main direction we have to take a look at this system to identify its components.
First one is the functionality of the system use cases point of view:

- xref:document-use-cases.adoc[Document]
- xref:organization-use-cases.adoc[Organization]
- xref:user-groups-use-cases.adoc[User Groups]
- xref:ingress-use-cases.adoc[Ingress]
- xref:data-source-use-cases.adoc[Data Source]
- xref:thesaurus-use-cases.adoc[Thesaurus]

Second, content point of view.

== Content