trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Sdk/Sdk.Core/**

pool: 'contabo'

variables:
  sdkCoreSolutionName: 'Sdk/Sdk.Core/Sdk.Core.sln'

stages:
  - stage: Variables
    jobs:
      - job:
        steps:
          - script: |
              echo $PATH
              env | sort

  - stage: Feature_branch
    condition: ne(variables['System.PullRequest.SourceBranch'], '')
    jobs:
      - job: restore_solution
        displayName: Restore Solution
        steps:
          - script: |
              echo "COMMAND===> dotnet restore Sdk/Sdk.Core/Sdk.Core.sln"
              dotnet restore Sdk/Sdk.Core/Sdk.Core.sln

      - job: build_solution
        displayName: Build Solution
        dependsOn: restore_solution
        steps:
          - script: |
              echo "COMMAND===> dotnet build Sdk/Sdk.Core/Sdk.Core.sln"
              dotnet build Sdk/Sdk.Core/Sdk.Core.sln

      - job: test_solution
        displayName: Test Solution
        dependsOn: build_solution
        steps:
          - script: |
              echo "COMMAND===> dotnet test Sdk/Sdk.Core/Sdk.Core.sln"
              dotnet test Sdk/Sdk.Core/Sdk.Core.sln

  - stage: Main_branch
    condition: and(eq(variables['System.PullRequest.SourceBranch'], ''), eq(variables['Build.SourceBranch'],'refs/heads/main'))
    jobs:
      - job: restore_solution
        displayName: Restore Solution
        steps:
          - script: |
              echo "COMMAND===> dotnet restore Sdk/Sdk.Core/Sdk.Core.sln"
              dotnet restore Sdk/Sdk.Core/Sdk.Core.sln

      - job: build_solution
        displayName: Build Solution
        dependsOn: restore_solution
        steps:
          - script: |
              echo "COMMAND===> dotnet build Sdk/Sdk.Core/Sdk.Core.sln"
              dotnet build Sdk/Sdk.Core/Sdk.Core.sln

      - job: test_solution
        displayName: Test Solution
        dependsOn: build_solution
        steps:
          - script: |
              echo "COMMAND===> dotnet test Sdk/Sdk.Core/Sdk.Core.sln"
              dotnet test Sdk/Sdk.Core/Sdk.Core.sln

      - job: install_semantic
        displayName: Install Semantic-Release
        dependsOn: test_solution
        steps:
          - script: |
              echo '##vso[task.prependpath]$(HOME)/.local/bin'
            displayName: PATH
          - script: |
              npm install npm
            displayName: install npm
          - script: |
              npm install semantic-release
            displayName: install semantic-release
          - script: |
              npm install @semantic-release/changelog
            displayName: install changelog
          - script: |
              npm install @semantic-release/exec
            displayName: install exec
          - script: |
              npm install @semantic-release/git
            displayName: install semantic-git
          - script: |
              npm install @semantic-release/github
            displayName: install semantic-github
          - script: |
              pip3 install --user bump2version
            displayName: install bump2version

      - job: semantic_release
        displayName: Semantic Release
        dependsOn: install_semantic
        steps:
          - script: |
              echo '##vso[task.prependpath]$(HOME)/.local/bin'
            displayName: PATH
          - script: |
              cp -f Sdk/Sdk.Core/.releaserc `pwd`
              ls -la
            displayName: copy .releaserc
          - script: |
              cp -f Sdk/Sdk.Core/.bumpversion.cfg `pwd`
              ls -la
            displayName: copy .bumpversion.cfg
          - script: |
              ls -la
              npx semantic-release --debug
            displayName: Semantic Release
            env:
              GH_TOKEN: $(githubToken)

      - job: nuget
        displayName: Nuget
        dependsOn: semantic_release
        workspace:
          clean: all
        steps:
          - script: |
              dotnet pack Sdk/Sdk.Core/Core/Core.csproj --configuration Release --include-symbols -p:NuspecFile=Sdk/Sdk.Core/Core/Core.nuspec
              dotnet pack Sdk/Sdk.Core/Model.Interfaces/Interfaces.csproj --configuration Release --include-symbols -p:NuspecFile=Sdk/Sdk.Core/Model.Interfaces/Interfaces.nuspec
            displayName: packaging
              
          - script: |
              dotnet nuget push Sdk/Sdk.Core/Core/bin/Release/EncyclopediaGalactica.Sdk.Core.`cat version.txt`.nupkg --api-key $GH_TOKEN --source "https://nuget.pkg.github.com/EncyclopediaGalactica/index.json" --skip-duplicate
              dotnet nuget push Sdk/Sdk.Core/Model.Interfaces/bin/Release/EncyclopediaGalactica.Sdk.Core.Model.Interfaces`cat version.txt`.nupkg --api-key $GH_TOKEN --source "https://nuget.pkg.github.com/EncyclopediaGalactica/index.json" --skip-duplicate
            displayName: publish nuget
            env:
              GH_TOKEN: $(githubToken)
              