title = "Polynomial Functions and Their Graphs"
reference = "polynomial_functions_and_their_graphs"
section_number = 3.2
chapter_reference = "3_polynomial_and_rational_functions"
book_reference = "james_stewart_precalculus"
page_start = 260
page_exercises_start = 271
concepts_questions_interval_start = "1"
concepts_questions_interval_end = "4"
skills_questions_interval_start = "5"
skills_questions_interval_end = "86"
applications_questions_interval_start = "87"
applications_questions_interval_end = "90"
discussion_questions_interval_start = "91"
discussion_questions_interval_end = "93"
page_end = 274
