title = "Modeling Harmonic Motion"
section_number = 5.6
chapter_reference = "5_trigonometric_functions_unit_circle_approach"
book_reference = "james_stewart_precalculus"
page_start = 458
page_exercises_start = 467
concepts_questions_interval_start = "1"
concepts_questions_interval_end = "4"
skills_questions_interval_start = "5"
skills_questions_interval_end = "38"
applications_questions_interval_start = "39"
applications_questions_interval_end = "58"
discussion_questions_interval_start = "59"
discussion_questions_interval_end = "60"
page_end = 472
