title = "Trigonometric Functions of Real Numbers"
section_number = 5.2
chapter_reference = "5_trigonometric_functions_unit_circle_approach"
book_reference = "james_stewart_precalculus"
page_start = 417
page_exercises_start = 424
concepts_questions_interval_start = "1"
concepts_questions_interval_end = "4"
skills_questions_interval_start = "5"
skills_questions_interval_end = "91"
applications_questions_interval_start = "92"
applications_questions_interval_end = "94"
discussion_questions_interval_start = "95"
discussion_questions_interval_end = "97"
page_end = 427
