@startuml C4_Elements

!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
' uncomment the following line and comment the first to use locally
'!include C4_Context.puml

title Encyclopedia Galactica Components

Person(personAlias, "User of the system", "This user can be simple user or administrator")
Container(webUI, "Web based user interface", "Blazor")
Container(bff, "Backend for Frontend Service", "Responsibility: orchestration of building up the data will be displayed on the user interface")
Container(documentApi, "The Document Api", "Responsibility: all the document related business logic")
ContainerDb(documentDb, "The Document Database", "PostgreSQL Database")
Container(iamApi, "The IAM Api", "Responsibility: providing functionalities to manage users and user rights and being part of the auth processes")
ContainerDb(iamDb, "The IAM Database", "PostgreSQL Database")
Container(sessionApi, "The Session Api", "Responsibility: storing and serving user sessions related data")
ContainerDb(sessionDb, "The Session Database", "PostgreSQL Database")

Rel(personAlias, webUI, "uses", "https")
Rel(webUI, bff, "requests data", "https")
Rel(bff, documentApi, "requests data", "https")
Rel(bff, iamApi, "requests data", "https")
Rel(bff, sessionApi, "requests data", "https")
Rel(documentApi, documentDb, "reads/writes", "")
Rel(iamApi, iamDb, "reads/writes", "")
Rel(sessionApi, sessionDb, "reads/writes", "")
@enduml