@startuml
'https://plantuml.com/use-case-diagram

'Actors
:content_consumer1: as "Content Consumer 1"
:content_consumer2: as "Content Consumer 2"
:content_owner: as "Content Owner"
:admin: as "Admin"

' Acts
(Create new Document) as (create_new_document)
(Edit Document) as (edit_document)
(Delete Document) as (delete_document)

(Publish/Unpublish Document) as (publish_unpublish_document)
(Share/Unshare Document) as (share_unshare_document)

(Create User Groups) as (create_user_groups)
(Add Members to User Group) as (add_members_to_user_group)
(Remove Members from User Group) as (remove_members_from_user_group)
(Delete User Groups) as (delete_user_groups)

(Add Ingress) as (add_ingress)
(Modify Ingress) as (modify_ingress)
(Delete Ingress) as (delete_ingress)

'Use cases
content_consumer1 --> (consume_content)
content_consumer2 --> (consume_content)
content_owner --> (manage_content)

'Notes
note right of (manage_content)
Manage content includes:
- adding new document
- creating new ingress

end note

note right of (consume_content)
Consume content means:
- create
- update
- delete
- annotate (adding links to other docs)
- share/publish
end note



:Main Admin: as Admin
(Use the application) as (Use)

User -> (Start)
User --> (Use)

Admin ---> (Use)

note right of Admin : This is an example.

note right of (Use)
A note can also
be on several lines
end note

note "This note is connected\nto several objects." as N2
(Start) .. N2
N2 .. (Use)
@enduml