[exercises]
database_connection_string = "postgres://exercises:3x3rc1s3s@localhost:5432/exercises"
catalog_path = "../../Modules/Exercises/text_book_catalog/"
generated_tests_path = "../../Modules/Exercises/text_book_catalog/generated_tests/"
