title = "Average Rate of Change of a Function"
section_number = 2.4
chapter_reference = "functions"
book_reference = "james_stewart_precalculus"
page_start = 185
page_exercises_start = 190
concepts_questions_interval_start = "1"
concepts_questions_interval_end = "6"
skills_questions_interval_start = "7"
skills_questions_interval_end = "28"
applications_questions_interval_start = "29"
applications_questions_interval_end = "38"
discussion_questions_interval_start = "39"
discussion_questions_interval_end = "39"
page_end = 192
