title = "Exponential and Logarithmic Equations"
section_number = 4.5
chapter_reference = "4_exponential_and_logarithmic_functions"
page_start = 369
page_exercises_start = 376
concepts_questions_interval_start = 1
concepts_questions_interval_end = 2
skills_questions_interval_start = 3
skills_questions_interval_end = 86
applications_questions_interval_start = 87
applications_questions_interval_end = 100
discussion_questions_interval_start = 101
discussion_questions_interval_end = 103
page_end = 378
