title = "Logarithmic Functions"
reference = "logarithmic_functions"
section_number = 4.3
chapter_reference = "4_exponential_and_logarithmic_functions"
book_reference = "james_stewart_precalculus"
page_start = 352
page_exercises_start = 359
concepts_questions_interval_start = "1"
concepts_questions_interval_end = "6"
skills_questions_interval_start = "7"
skills_questions_interval_end = "101"
applications_questions_interval_start = "102"
applications_questions_interval_end = "107"
discussion_questions_interval_start = "108"
discussion_questions_interval_end = "112"
page_end = 362
