= Document

A document describes a medium containing information.
We have to make distinction between the physical format and information formality.
The physical format is paper, CD, DVD or something like that.
While the information formality can be contract, book or any defined format.
Just think of the pre-defined structure provided by LaTeX.
But the formality and physical representation are two distinct thing.
From Encyclopedia Galactica point of view the Document is by default a digital format, so physical attributes don't play a role here, and formality like contract.

In the scope of Encyclopedia Galactica system the Document is the structure of the information.

The other, and similarly important aspect of this structure is the data input.
Imagine people recording the data, for example addresses, but the data has a big variation.
The mentioned address formula is changing country-by-country and we have to provide the right user interface for our users to be able to do their job well.
In order to know what data structure is needed for a certain country with what input data validation we need to know exactly what that data structure looks like.
Document has the responsibility to be a container where this data is available.

We want to know the following details:

== Id

In the system every Document gets a unique identifier.

== Name

In the system every Document gets a name.

== Description

Every Document has some level of description

== Source

The Source of the Document

== Structure

Every Document has its own unique structure.