title = "Trigonometric Graphs"
section_number = 5.3
chapter_reference = "5_trigonometric_functions_unit_circle_approach"
book_reference = "james_stewart_precalculus"
page_start = 427
page_exercises_start = 439
concepts_questions_interval_start = "1"
concepts_questions_interval_end = "4"
skills_questions_interval_start = "5"
skills_questions_interval_end = "86"
applications_questions_interval_start = "87"
applications_questions_interval_end = "90"
discussion_questions_interval_start = "91"
discussion_questions_interval_end = "93"
page_end = 442
