title = "Chapter Review"
section_number = 2.9
chapter_reference = "functions"
book_reference = "james_stewart_precalculus"
page_start = 234
page_exercises_start = 234
concepts_questions_interval_start = "1"
concepts_questions_interval_end = "16"
skills_questions_interval_start = "1"
skills_questions_interval_end = "111"
applications_questions_interval_start = "NA"
applications_questions_interval_end = "NA"
discussion_questions_interval_start = "NA"
discussion_questions_interval_end = "NA"
page_end = 240
