title = "Chapter Test"
section_number = 3.9
chapter_reference = "3_polynomial_and_rational_functions"
page_start = 330
page_exercises_start = 330
concepts_questions_interval_start = 1
concepts_questions_interval_end = 15
skills_questions_interval_start = "NA"
skills_questions_interval_end = "NA"
applications_questions_interval_start = "NA"
applications_questions_interval_end = "NA"
discussion_questions_interval_start = "NA"
discussion_questions_interval_end = "NA"
page_end = 331
