title = "Linear Functions and Models"
section_number = 2.5
chapter_reference = "functions"
book_reference = "james_stewart_precalculus"
page_start = 193
page_exercises_start = 198
concepts_questions_interval_start = "1"
concepts_questions_interval_end = "6"
skills_questions_interval_start = "7"
skills_questions_interval_end = "38"
applications_questions_interval_start = "39"
applications_questions_interval_end = "52"
discussion_questions_interval_start = "53"
discussion_questions_interval_end = "54"
page_end = 200
