site:
  title: Encyclopedia Galactica
  url: https://encyclopediagalactica.github.io/EncyclopediaGalactica
  start_page: encyclopedia-galactica-doc::start-page.adoc
asciidoc:
  extensions:
    - asciidoctor-plantuml
  attributes:
    plantuml-server-url: "https://plantuml.gitlab-static.net"
#    plantuml-fetch-diagram: true
content:
  sources:
    - url: ./../..
      start_path: Doc/antora
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll