site:
  title: Encyclopedia Galactica System
  url: https://encyclopediagalactica.github.io
#  start_page: encyclopedia-galactica-doc::start-page.adoc
content:
  sources:
    - url: ./../..
      start_path: Doc/antora
ui:
  bundle: 
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: 
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll