title = "Mathematics Examination - 2023 - May - Medium level - Hungarian"
reference = "mathematics_examination_2023_may_medium_hungarian"
section_number = 2008.1
chapter_reference = "mathematics_examination_medium"
book_reference = "high_school_graduation_mathematics"
page_start = 1
page_exercises_start = 10
concepts_questions_interval_start = "NA"
concepts_questions_interval_end = "NA"
skills_questions_interval_start = "1"
skills_questions_interval_end = "12"
applications_questions_interval_start = "NA"
applications_questions_interval_end = "NA"
discussion_questions_interval_start = "NA"
discussion_questions_interval_end = "NA"
page_end = 10
