title = "One-to-One Functions and Their Reverses"
reference = "one_to_one_functions_and_their_reverses"
section_number = 2.8
chapter_reference = "functions"
book_reference = "james_stewart_precalculus"
page_start = 224
page_exercises_start = 231
concepts_questions_interval_start = "1"
concepts_questions_interval_end = "6"
skills_questions_interval_start = "7"
skills_questions_interval_end = "98"
applications_questions_interval_start = "99"
applications_questions_interval_end = "107"
discussion_questions_interval_start = "108"
discussion_questions_interval_end = "112"
page_end = 234
