title = "Chapter Review"
section_number = 3.8
chapter_reference = "3_polynomial_and_rational_functions"
book_reference = "james_stewart_precalculus"
page_start = 324
page_exercises_start = 324
concepts_questions_interval_start = "1"
concepts_questions_interval_end = "15"
skills_questions_interval_start = "1"
skills_questions_interval_end = "109"
applications_questions_interval_start = "NA"
applications_questions_interval_end = "NA"
discussion_questions_interval_start = "NA"
discussion_questions_interval_end = "NA"
page_end = 324
