title = "More Trigonometric Graphs"
reference = "more_trigonometric_graphs"
section_number = 5.4
chapter_reference = "5_trigonometric_functions_unit_circle_approach"
book_reference = "james_stewart_precalculus"
page_start = 442
page_exercises_start = 449
concepts_questions_interval_start = "1"
concepts_questions_interval_end = "2"
skills_questions_interval_start = "3"
skills_questions_interval_end = "64"
applications_questions_interval_start = "65"
applications_questions_interval_end = "66"
discussion_questions_interval_start = "67"
discussion_questions_interval_end = "69"
page_end = 450
