title = "Modeling with Exponential Functions"
section_number = 4.6
chapter_reference = "4_exponential_and_logarithmic_functions"
page_start = 379
page_exercises_start = 387
concepts_questions_interval_start = "NA"
concepts_questions_interval_end = "NA"
skills_questions_interval_start = "NA"
skills_questions_interval_end = "NA"
applications_questions_interval_start = 1
applications_questions_interval_end = 35
discussion_questions_interval_start = "NA"
discussion_questions_interval_end = "NA"
page_end = 391
