title = "Algebraic expressions"
section_number = 1.3
chapter_reference = "fundamentals"
book_reference = "james_stewart_precalculus"
page_start = 25
page_exercises_start = 33
concepts_questions_interval_start = "1"
concepts_questions_interval_end = "8"
skills_questions_interval_start = "9"
skills_questions_interval_end = "143"
applications_questions_interval_start = "143"
applications_questions_interval_end = "144"
discussion_questions_interval_start = "145"
discussion_questions_interval_end = "148"
page_end = 35
