name: Backend Release branch build
run-name: backend_release_branch_build

on:
  push:
    branches:
      - main
    paths:
      - 'src/EG.Backend/**'

jobs:
  
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "============="
          echo "=== Debug ==="
          echo "============="
          echo "github ref: " ${{ vars.GITHUB_REF }}
          echo "dotnet version: " ${{ vars.DOTNET_VERSION }}
          echo "event name: " ${{ github.event_name }}
          
  main_branch:
    name: Main Branch Build
    runs-on: ubuntu-latest
    needs: debug
    
    steps:
      - uses: actions/checkout@v3
        
      - name: Setting up Dotnet with ${{ vars.DOTNET_VERSION }} version
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: EG Nuget repo
        run: |
          dotnet nuget add source --username Andras-Csanyi --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/EncyclopediaGalactica/index.json"
          
      - name: Restore
        run: |
          dotnet restore src/EG.Backend/EG.Backend.sln
          
      - name: Build
        run: |
          dotnet build --configuration Release --no-restore src/EG.Backend/EG.Backend.sln
          
      - name: Test
        run: |
          dotnet test --no-restore --verbosity normal src/EG.Backend/EG.Backend.sln
          