name: Documentation - Main
run-name: Documentation - Main

on:
  push:
    branches:
      - main
    paths:
      - 'Docs/**'
        
jobs:
  
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "============="
          echo "=== Debug ==="
          echo "============="
          echo "github ref: " ${{ vars.GITHUB_REF }}
          echo "dotnet version: " ${{ vars.DOTNET_VERSION }}
          echo "event name: " ${{ github.event_name }}
  
  main_branch:
    name: Main Branch Build
    runs-on: ubuntu-latest
    needs: debug
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      pages: write
      id-token: write
    
    steps:
      - uses: actions/checkout@v4

      - run: dotnet tool update -g docfx

      - run: docfx Docs/docfx.json --output Docs/_site

      - name: Setup pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_SEMANTIC_RELEASE }}
        with:
          path: 'Docs/_site'

      - name: Deploy to Github Pages
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_SEMANTIC_RELEASE }}
        id: deployment
        uses: actions/deploy-pages@v2
      