name: Feature Branch Build
run-name: Feature Branch Build

on:
  pull_request:
    branches:
      - main

jobs:
  
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "============="
          echo "=== Debug ==="
          echo "============="
          echo "github ref: " ${{ vars.GITHUB_REF }}
          echo "event name: " ${{ github.event_name }}
  
  feature_branch:
    name: Feature Branch Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Setting up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'

      - name: mvn clean package
        run: |
          mvn clean package