name: Dotnet Main Branch Build
run-name: Dotnet Main Branch Build

on:
  push:
    branches:
      - main
    paths:
      - 'src/dotnet/**'

jobs:
  
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "============="
          echo "=== Debug ==="
          echo "============="
          echo "github ref: " ${{ vars.GITHUB_REF }}
          echo "dotnet version: " ${{ vars.DOTNET_VERSION }}
          echo "event name: " ${{ github.event_name }}
          
  main_branch:
    name: Main Branch Build
    runs-on: ubuntu-latest
    needs: debug
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions: 
      contents: write
      issues: write
      pull-requests: write
      pages: write
      id-token: write
    
    steps:
      - uses: actions/checkout@v3
        
      - name: Setting up Dotnet with ${{ vars.DOTNET_VERSION }} version
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}
          
      - name: Restore
        run: |
          dotnet restore src/dotnet/EncyclopediaGalactica.sln
          
      - name: Build
        run: |
          dotnet build --configuration Release --no-restore src/dotnet/EncyclopediaGalactica.sln
          
      - name: Test
        run: |
          dotnet test --no-restore --verbosity normal src/dotnet/EncyclopediaGalactica.sln
